# Generated by Django 3.1.4 on 2020-12-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=50)),
                ('Nick', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=100)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Llave_publica', models.CharField(max_length=2048)),
                ('Llave_privada', models.CharField(max_length=2048)),
                ('Iv', models.CharField(max_length=16)),
            ],
        ),
    ]
