# Generated by Django 3.1.4 on 2020-12-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0002_auto_20201218_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Iv',
            field=models.CharField(max_length=1024),
        ),
    ]
